name: Deploy to AWS

on:
  push:
    branches:
      - master # Change to your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Build Frontend (React + Vite)
        run: |
          cd client
          npm install
          npm run build

      - name: Deploy to AWS via SSH
        env:
          AWS_HOST: ${{ secrets.AWS_HOST }}
          AWS_USER: ${{ secrets.AWS_USER }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          ssh -o StrictHostKeyChecking=no -i private_key.pem $AWS_USER@$AWS_HOST << 'EOF'
            # Update system and install dependencies
            sudo apt update && sudo apt install -y nginx nodejs npm
            
            # Clone or pull latest changes
            cd /var/www/ai-nexus || (sudo git clone https://github.com/Sarthaksriv1411/ai-nexus-sarthak.git /var/www/ai-nexus && cd /var/www/ai-nexus)
            sudo git reset --hard
            sudo git pull origin main

            # Setup Frontend
            cd client
            npm install
            npm run build
            sudo cp -r dist/* /var/www/html/

            # Setup Backend
            cd ../server
            npm install
            pm2 stop all || true
            pm2 start index.js --name ai-nexus-backend

            # Restart Nginx
            sudo systemctl restart nginx
          EOF

      - name: Cleanup Private Key
        run: rm -f private_key.pem
