name: Deploy to AWS

on:
  push:
    branches:
      - master # Change to your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Build Frontend (React + Vite)
        run: |
          cd src
          npm install
          npm run build

      - name: Deploy to AWS via SSH
        env:
          AWS_HOST: ${{ secrets.EC2_HOST }}
          AWS_USER: ${{ secrets.EC2_USER }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

        run: |
          echo "$SSH_PRIVATE_KEY" > ai-nexus-sarthak.pem
          chmod 600 ai-nexus-sarthak.pem
          
          ssh -o StrictHostKeyChecking=no -i private_key.pem $AWS_USER@$AWS_HOST << 'EOF'
            # Ensure deployment directory exists
            sudo mkdir -p /var/www/ai-nexus
            cd /var/www/ai-nexus

            # Clone or update the repository
            if [ ! -d ".git" ]; then
              sudo git clone https://github.com/YOUR_USERNAME/ai-nexus.git .
            else
              sudo git reset --hard
              sudo git pull origin main
            fi

            # Setup Frontend
            cd src
            npm install
            npm run build
            sudo cp -r dist/* /var/www/html/

            # Setup Backend
            cd ../backend
            npm install

            # Install PM2 and Restart Backend
            sudo npm install -g pm2
            pm2 stop ai-nexus-backend || true
            pm2 start index.js --name ai-nexus-backend
            pm2 save

            # Restart Nginx
            sudo systemctl restart nginx
          EOF

      - name: Cleanup Private Key
        run: rm -f private_key.pem